VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Prm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit
Public Nm$
Public TyChr$
Public IsAy As Boolean
Public IsPrmAy As Boolean
Public IsOpt As Boolean
Public IsByVal As Boolean
Public AsTy$
Public DftStr$
